[package]
name = "spotify-adblock"
version = "1.1.0"
authors = ["abba23"]
description = "Adblocker for Spotify"
edition = "2024"

[dependencies]
libc = "*"
regex = "*"
serde = { version = "*", features = ["derive"] }
serde_regex = "*"
log = "*"
env_logger = "*"
toml = "*"
dirs = "*"

[lib]
name = "spotifyadblock"
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 3
panic = "abort"
