denylist = [
    'https://.*-spclient\.spotify\.com/ads/.*', # ads
    'https://.*-spclient\.spotify\.com/ad-logic/.*', # ads
    'https://spclient\.wg\.spotify\.com/ads/.*', # ads
    'https://spclient\.wg\.spotify\.com/ad-logic/.*', # ads
    'https://spclient\.wg\.spotify\.com/gabo-receiver-service/.*', # tracking
]
