name: release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
    - name: Run make
      run: make
    - name: Attach build artifact to release
      run: |
        mv target/release/libspotifyadblock.so spotify-adblock.so
        gh release upload --clobber "${{ github.event.release.tag_name }}" spotify-adblock.so
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
